# This is a basic workflow to help you get started with Actions

name: Build and Push Docker Image to Docker Hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]
  workflow_dispatch:
    inputs:
      secret-name:
        default: 'DOCKERHUB_USERNAME'
        required: true
      secret-value:
        default: 'DOCKERHUB_TOKEN'
        required: true
      repo-name:
        description: 'Repo Name'
        default: quickorder-backend
        required: true
        
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:         
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 28101976
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: quickorder-backend:latest
          secrets: |
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
            DOCKERHUB_USERNAME: 28101976
      - name: Inspect
        run: |
          docker image inspect quickorder-backend:latest
